FROM rust:1.81

RUN rustup component add rustfmt

RUN apt update && apt install -y build-essential llvm clang cmake
RUN rustup target add wasm32-unknown-unknown
RUN cargo install --locked radix-clis@1.3.0